### ISSUE TITLE
Setup Routing for react app

### ISSUE THREAD

**Issue by Harshal141** [Harshal141/ResumeWorded#3]
The frontend requires the addition of different routes:
`react-router-dom`
Objective: Implement routing for pages:
- Home Page: Consists of element <Navbar> and <MDEditro> `\editor`
- Profile Page: This is not coded so please create any template file `\dashboard`
- Explore Page: This is not coded so please create any template file `\community`

**Comment by Faisalhs51** [comment]
@Harshal141 assign this to me
