### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Harshal141** [Harshal141/ResumeWorded#4]
The repository requires general instructions about how people can contribute to this project.

General instruction:
- How to set up the project.
- How they can communicate through issues.
- How to create pull requests etc (Make sure to create pulls to the `master` branch only)

**Comment by ira-mane** [comment]
Hello @Harshal141 ,Can you assign me this issue ?

**Comment by Harshal141** [comment]
Ok you can work on it

**Comment by Harshal141** [comment]
@ira-mane can you set a deadline for this task. 
Thank you

**Comment by ira-mane** [comment]
> @ira-mane can you set a deadline for this task. Thank you

Sure , I will complete the task by today or max tomorrow afternoon.

**Comment by Harshal141** [comment]
Added comments to your PR @ira-mane

**Comment by Harshal141** [comment]
Clossing this one for now
