### ISSUE TITLE
Setup Tailwind + ESlint

### ISSUE THREAD

**Issue by Harshal141** [Harshal141/ResumeWorded#6]
> *Make sure to apply eslint for code styling only and not for enforcement.*

ESlint: https://eslint.org/
Tailwind: https://tailwindcss.com/

- Setup tailwind for the react app in `client` folder
- Apply linting for both `server` as well as `client`
- Add instructions for running linting in readme.

**Comment by realshantanu** [comment]
Assign me this task I will setup tailwind for this project
