### ISSUE TITLE
Bugs in Navbar and Footer

### ISSUE THREAD

**Issue by guntarakesh** [Harshal141/ResumeWorded#7]
I  want to make Navbar fixed and enhance the UI of footer .

**Comment by guntarakesh** [comment]
@Harshal141  Assign this issue to me , i can work on it .

**Comment by Harshal141** [comment]
Make sure it has all the links working to all the pages that are present in code. 

You can take reference for the design of navbar from Figma (Link attached at the end of readme)

**Comment by Harshal141** [comment]
@guntarakesh you can take reference from this image to what we want as the final design.

![image](https://github.com/Harshal141/ResumeWorded/assets/91362856/0f5c06f1-8392-43e9-947a-c327b9fc911e)

**Comment by guntarakesh** [comment]
ok  , i will update all Links related to website .

**Comment by guntarakesh** [comment]
> @guntarakesh you can take reference from this image to what we want as the final design.
> 
> ![image](https://user-images.githubusercontent.com/91362856/272340618-0f5c06f1-8392-43e9-947a-c327b9fc911e.png)

i did not understand what i have to take reference from this image ? , there is nothing in this image .

**Comment by Harshal141** [comment]
In the top of that image there is a bar with dashboard upload profile etc. 

Can update the current navbar to look like this one?

**Comment by Harshal141** [comment]
@guntarakesh can you set a deadline for this task, because some other tasks are blocked due to this.

**Comment by guntarakesh** [comment]
@Harshal141 i can complete the Navbar part within 1-2 days , but I am not knowing exactly what Navbar contains and what is their features ?

**Comment by Harshal141** [comment]
Just design the navbar as mentioned in image with buttons for links given below @guntarakesh.

"/"
"/dashboard"
"/community"
"/resume"

Just to remind again this is the navbar design
![image](https://github.com/Harshal141/ResumeWorded/assets/91362856/0fe1efba-531f-4039-b880-b2f1f57a16de)

If you have difficulty understanding for now just design the navbar, we can look into the functionality later.

**Comment by guntarakesh** [comment]
@Harshal141  ok then I will design the Navbar with the mentioned paths .

**Comment by guntarakesh** [comment]
@Harshal141  sir , I cloned the my fork Repo , how to start the client i used the commands given in scripts but its showing errors.

**Comment by Harshal141** [comment]
The react project is in clients folder.
```
cd client
npm i
npm start
```
This will do.

**Comment by guntarakesh** [comment]
@Harshal141 ,  I made it and looking like this , if its okay to you then I will make a PR , if there are any changes please mention them . 
![image](https://github.com/Harshal141/ResumeWorded/assets/99466056/5b2a3a71-0a12-4b7f-a2fc-9f5a5e06b650)

**Comment by Harshal141** [comment]
This is nowhere near the finished one, 
![image](https://github.com/Harshal141/ResumeWorded/assets/91362856/581feda1-8099-442e-b6e7-53f55acb0d01)
This should be the final product, and make sure it is responsive. You can use tailwind in this.

**Comment by guntarakesh** [comment]
Okay I will update it .

**Comment by guntarakesh** [comment]
@Harshal141  , I updated the Navbar and it is responsive too . 

please have a look at it , 
This is Responsive too . 


![image](https://github.com/Harshal141/ResumeWorded/assets/99466056/9d16e0e7-9a22-49ae-b7e0-a942264839d4)
![image](https://github.com/Harshal141/ResumeWorded/assets/99466056/d899043e-527b-4da7-8410-666c0e118e30)
![image](https://github.com/Harshal141/ResumeWorded/assets/99466056/2dcbbb80-74c8-4a8f-8d09-1c401bf2a2c7)

**Comment by Harshal141** [comment]
Can you keep the color of the buttons same as in the image. 
Use color picker extension to extract it from the image. 

Dashboard has a logo to it's left that you missed. And it's publish resume not resume in the right most button. 

Rest is good you can create a pr after adding above changes.

**Comment by guntarakesh** [comment]
@Harshal141 i created a PR , Please Review it .

**Comment by guntarakesh** [comment]
@Harshal141 again i created the PR , once review it .

**Comment by Harshal141** [comment]
I have merged the PR for now.
Congrats and thank you for your contribution. 🙏

@guntarakesh

**Comment by guntarakesh** [comment]
@Harshal141 can you please give the Hacktoberfest-Accepted Label .
